### ISSUE TITLE
how to get cookies.txt

### ISSUE THREAD

**Issue by qqrey** [emako/bilibili-mp3#1]
version.print_version()
if os.path.exists('cookies.txt'):
    print('cookies file detected.')
else:
    print('cookies file not detected.')
    print("copy the 'cookies.txt' file to the same path when necessary.")

In my case,I have download a mp3 by your application.But when I try to download the second mp3,it say i have no cookies file.The extension also down.If I have no cookies.txt,how can I download the first mp3,but if I have cookies.txt,why I can't continue download else mp3

**Comment by qqrey** [comment]
I realize that it just the series video like 拜年祭 can't download,else video can download normally

here is the song I wanted to download
https://www.bilibili.com/video/BV1bR4y1a7eW/?spm_id_from=333.999.0.0

**Comment by emako** [comment]
Here are some step for get `cookies.txt` and how to use it.

1. Install the chrome extension from `cookiestxt.crx`, and use it like following.

![image](https://user-images.githubusercontent.com/24737061/234781523-e85ccab4-ab10-4cce-9fe8-91e341df20d6.png)

![image](https://user-images.githubusercontent.com/24737061/234782605-ae8b376f-4724-4eab-86a1-a7d183131099.png)

2. Copy the `cookies.txt` file to the same path as bilibili-mp3.
3. Copy the url `https://www.bilibili.com/video/BV1bR4y1a7eW/?spm_id_from=333.999.0.0` and launch `bilibili-mp3.exe`.

**Comment by emako** [comment]
You must have a 大会员 to support 4K audio track downloads.

**Comment by emako** [comment]
> I realize that it just the series video like 拜年祭 can't download,else video can download normally
> 
> here is the song I wanted to download https://www.bilibili.com/video/BV1bR4y1a7eW/?spm_id_from=333.999.0.0

It seems that you-get not support this type of video.

**Comment by qqrey** [comment]
But, some video like this
https://www.bilibili.com/video/BV1FB4y1T7dr/?spm_id_from=333.999.top_right_bar_window_default_collection.content.click&vd_source=7abc33268955f611afe5cfc6aadb5894

also can't download, I can't find any different or special compared to other normal videos

**Comment by emako** [comment]
I tracked the Network, and it seems that the Bilibili has recently changed its rules.
In that case, we have to wait for `you-get` to update.

**Comment by emako** [comment]
![image](https://user-images.githubusercontent.com/24737061/235385970-96f37b0d-14f2-4fdc-ba4e-44bf2ac4f30a.png)
I remember wrong. Dont use all cookies.

**Comment by emako** [comment]
![image](https://user-images.githubusercontent.com/24737061/235386551-f11a2290-ab5d-4010-ad4c-b356a15a990f.png)
But 拜年祭 can't download.
